"""complete baseline with file and link versions

Revision ID: 0001
Revises: 
Create Date: 2026-09-07 14:20:33.699809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('microsoft_sub', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub'),
    sa.UniqueConstraint('microsoft_sub')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_approved_version_id', sa.UUID(), nullable=True),
    sa.Column('reminder_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_locations_slug', 'locations', ['slug'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('file_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), server_default='file', nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('link_mode', sa.String(length=20), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("(kind = 'file' AND original_filename IS NOT NULL AND content_type IS NOT NULL AND file_size_bytes IS NOT NULL AND s3_key IS NOT NULL AND link_url IS NULL AND link_mode IS NULL) OR (kind = 'link' AND original_filename IS NULL AND content_type IS NULL AND file_size_bytes IS NULL AND s3_key IS NULL AND link_url IS NOT NULL AND length(trim(link_url)) > 0 AND link_mode IS NOT NULL AND link_mode = 'redirect')", name='ck_file_versions_payload'),
    sa.CheckConstraint("kind IN ('file', 'link')", name='ck_file_versions_kind'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'superseded')", name='ck_file_versions_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'version_number')
    )
    op.create_index('idx_file_versions_location_status', 'file_versions', ['location_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_file_versions_pending', 'file_versions', ['status', 'uploaded_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # Complete the circular reference only after both tables exist.
    op.create_foreign_key(
        'fk_locations_current_approved_version', 'locations', 'file_versions',
        ['current_approved_version_id'], ['id'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_locations_current_approved_version', 'locations', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_versions_pending', table_name='file_versions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_file_versions_location_status', table_name='file_versions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('file_versions')
    op.drop_index('idx_locations_slug', table_name='locations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('locations')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
