"""add oauth columns to admin_user

Revision ID: 9d9d693d9c91
Revises: 
Create Date: 2026-07-04 01:31:18.035395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9d693d9c91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('microsoft_sub', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.alter_column('admin_users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'admin_users', ['microsoft_sub'])
    op.create_unique_constraint(None, 'admin_users', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.alter_column('admin_users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('admin_users', 'google_sub')
    op.drop_column('admin_users', 'microsoft_sub')
    # ### end Alembic commands ###
